### ISSUE TITLE
Crash #14 BodyFatFragment.java line 410

### ISSUE THREAD

**Issue by serhii-pokrovskyi** [serhii-pokrovskyi/4Weight#27]
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void android.text.TextWatcher.beforeTextChanged(java.lang.CharSequence, int, int, int)' on a null object reference
       at android.widget.TextView.sendBeforeTextChanged(TextView.java:10561)
       at android.widget.TextView.setText(TextView.java:5891)
       at android.widget.TextView.setText(TextView.java:5847)
       at android.widget.EditText.setText(EditText.java:138)
       at android.widget.TextView.setText(TextView.java:5804)
       at com.mobismarthealth.a4weight.ui.main.fat.BodyFatFragment.buildData(BodyFatFragment.java:410)
       at com.mobismarthealth.a4weight.ui.main.fat.BodyFatPresenter.useSaved(BodyFatPresenter.java:77)
       at com.mobismarthealth.a4weight.ui.main.fat.BodyFatPresenter.lambda$start$1(BodyFatPresenter.java:63)
       at com.mobismarthealth.a4weight.ui.main.fat.BodyFatPresenter.lambda$BN5TC4IY2rMT1sExHqMUBanJIKY(Unknown Source)
       at com.mobismarthealth.a4weight.ui.main.f.-$$Lambda$e$BN5TC4IY2rMT1sExHqMUBanJIKY.onUserLoaded(Unknown Source:2)
       at com.mobismarthealth.a4weight.data.data.source.local.AppLocalDataSource.getUser(AppLocalDataSource.java:43)
       at com.mobismarthealth.a4weight.data.data.source.local.AppLocalDataSource.lambda$TMUnYZqZ0t1iinlk4rrcBbPYkME(Unknown Source)
       at com.mobismarthealth.a4weight.b.b.b.a.-$$Lambda$a$TMUnYZqZ0t1iinlk4rrcBbPYkME.run(Unknown Source:4)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by serhii-pokrovskyi** [comment]
Incorrect remove text watcher methods
fixed
